### ISSUE TITLE
Better error handling

### ISSUE THREAD

**Issue by crab2313** [nibon7/selinux-rs#5]
Currently, we just use Option<_> or a wrapped libc errno as the returned value of functions. Should we provide a more sophisticated Error type as the possible returned Result?

**Comment by nibon7** [comment]
yes,but we can only get the detailed error message from the low level c errno.

**Comment by crab2313** [comment]
Some functions wrapped by wrap_set_con do not set `errno` on failure. We should put forward another way to address the issue.
